version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    image: yatrimotorcycles/np-goverment-api-server:v1
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3005
    ports:
      - "3005:3005"
